[object_store]
type = "s3"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
endpoint = "http://minio:9000"
bucket = "seafowl"

[catalog]
type = "sqlite"
dsn = "/data/seafowl/db/seafowl.sqlite"
# Set journalling to DELETE mode instead of WAL
journal_mode = "delete"

[frontend.http]
bind_host = "0.0.0.0"
read_access = "any"
write_access = "any"
