[object_store]
type = "s3"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
endpoint = "https://minio:9000"
bucket = "seafowl"

[catalog]
type = "sqlite"
dsn = "sqlite:///data/seafowl/db/seafowl.sqlite?mode=ro"
# Disable journalling to get LiteFS working
journal_mode = "off"

[frontend.http]
bind_host = "0.0.0.0"
bind_port = "80"
read_access = "any"
write_access = "off"
