[object_store]
type = "s3"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
endpoint = "http://minio:9000"
bucket = "seafowl"

[catalog]
type = "sqlite"
dsn = "/data/seafowl/db/seafowl.sqlite"
# Run SQLite in read-only mode and disable journaling
journal_mode = "off"
read_only = true

[frontend.http]
bind_host = "0.0.0.0"
read_access = "any"
write_access = "off"
