DROP TABLE function;
DROP TABLE table_region;
DROP TABLE physical_region_column;
DROP TABLE physical_region;
DROP TABLE table_column;
DROP TABLE table_version;
DROP TABLE table;
DROP TABLE collection;
DROP TABLE database;