services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-08-13T21-54-44Z
    command: server --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: seafowl
      MINIO_ROOT_PASSWORD: seafowl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data

  seafowl-writer:
    build:
      dockerfile: seafowl/Dockerfile
    ports:
      - "8080:80"
    image: litestream-seafowl
    volumes:
      - ./configs/seafowl-writer:/etc/seafowl

volumes:
  minio-data: {}
