[package]
name = "object_store_factory"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.64"
futures = "0.3.30"
object_store = { version = "0.10.1", features = ["aws", "azure", "gcp"] }
tempfile = "3.10.1"

tracing = { workspace = true }
tracing-log = "0.2"
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
url = "2.5"
